### ISSUE TITLE
dataset link broken

### ISSUE THREAD

**Issue by zhiwenfan** [lrnzgiusti/MaRF#2]
Hi authors, thanks for bringing this amazing work!
Just want to know that if you can repost the datalink? As the mentioned "rover_unprepared - unprepared dataset ready for pipeline.py
rover_prepared - dataset ready for Uncertainty/Energy/PSNR modules" are not able to visit.

Bests,
Zhiwen

**Comment by lrnzgiusti** [comment]
Hi Zhiwen, 

Thanks for your interest in our work.

Sure, can you tell me the links that seem to be broken?

**Comment by zhiwenfan** [comment]
Thanks for the reply, the link "https://github.com/marsai2/mars-metaverse" and "https://github.com/marsai2/mars-metaverse/tree/main/scripts/preprocessing#preprocessing-steps" are seems broken. Is it possible to send me a copy of that dataset to my email "zhiwenfan@utexas.edu"?

Many thanks in advance!

**Comment by zhiwenfan** [comment]
I was also looking for data in the "/mars2020/mars2020_mastcamz_ops_raw/" directory on [pds.nasa.gov](http://pds.nasa.gov/), as indicated in your paper. However, I couldn't locate it through the keyword search.

Additionally, I noticed that the GitHub link you provided in your repository, "https://github.com/marsai2/mars-metaverse," is broken, and I am unable to access it.

Could you kindly provide guidance on how to access the data mentioned in your paper? Also, if possible, I would greatly appreciate it if you could share the raw data used in Figure 7 of your paper.

Thank you very much for your assistance.

**Comment by lrnzgiusti** [comment]
Hi Zhiwen, 

We should have updated the links within the repository.

For the M2020 data,  he sols can be found at:

https://pds-imaging.jpl.nasa.gov/data/mars2020/mars2020_mastcamz_ops_raw/browse/sol/ 

Which as of today, redirects automatically to:

https://planetarydata.jpl.nasa.gov/img/data/mars2020/mars2020_mastcamz_ops_raw/browse/sol/

We updated the URLs to fetch the data from the new link and redirect the pointers from the mars-metaverse repo to this repo here. 

https://github.com/lrnzgiusti/MaRF/blob/1f791797eaeea17c45d4175f8eeb22c953eb138e/scripts/preprocessing/pull_sols.py#L18-L24

Let me know if I can help you further!

**Comment by zhiwenfan** [comment]
Many thanks!
