### ISSUE TITLE
i want to get your original dataset

### ISSUE THREAD

**Issue by xiaoc57** [lrnzgiusti/MaRF#3]
Can you share a Google download link for the dataset used in the paper?

**Comment by houyongkuo** [comment]
I saw from the paper that the data should come from NASA's Planetary Data System (PDS), but I can only locate this page (https://ode.rsl.wustl.edu/mars/productsearch). I haven't found which dataset it is yet.

**Comment by houyongkuo** [comment]
Duplicate of #2

**Comment by lrnzgiusti** [comment]
Thanks! Actually I recommend to look for new acquisitions on the pds:

https://planetarydata.jpl.nasa.gov/img/data/mars2020/
